exclude:
  - docker-compose.yml
  - README.md
  - notes.txt
sass:
    sass_dir: _sass
url: "https://blog.pinarydevelopment.com"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
paginate: 10
title: Pinary Development - A class above binary
repository: PinaryDevelopment/blog
