version: '3.8'

services:
  jekyll:
      image: jekyll/jekyll:pages
      command: jekyll serve --watch --incremental --force_polling
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll
# C:\code\z\pinarydevelopment.github.io> docker-compose up
